# Basic Information 
title: Jialin Cui
position: Ph.D. in Computer Science
affiliation: North Carolina State University
email: jcui9@ncsu.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: jialinc, jialin cui, jialin cui, jialin cui ncsu, jialin cui north carolina state university, jialin cui homepage, jialin cui personal website, jialin cui academic homepage
description: Personal academic homepage.
canonical: https://jialinc.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=tCuaIgYAAAAJ&hl=en
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/JialinC
linkedin: https://linkedin.com/in/cui-jialin
leetcode: https://leetcode.com/u/J__C/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: UA-111540567-4

# remote_theme: yaoyao-liu/minimal-light
remote_theme: pages-themes/hacker
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
